name: Python application matrix

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ '3.9' ]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [[ -f requirements.txt ]]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
  e2e:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Run simple_math.py
      run: |
        export CMD_VALUE="python simple_math.py 4 5"
        export OUTPUT=$(CMD_VALUE)

        cat simple_math.py >> $GITHUB_STEP_SUMMARY
        cat simple_math.py >> out.py

        echo "" >> $GITHUB_STEP_SUMMARY
        echo "$CMD_VALUE" >> $GITHUB_STEP_SUMMARY
        echo "O/P: ${OUTPUT}" >> $GITHUB_STEP_SUMMARY

        echo "# ${CMD_VALUE}\n#O/P: ${OUTPUT}" >> out.py
    - name: Upload coverage data
      uses: actions/upload-artifact@v3
      with:
        name: out.txt
        path: out.txt
        if-no-files-found: error    
  
